services:
  - type: web
    name: nowgoal-scraper
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PROXY_URL
        value: "URL_DE_TU_PROXY" # ¡¡IMPORTANTE!! Reemplaza esto con la URL de tu servicio de proxy